language: swift

branches:
 only:
 - master

xcode_project: Dequable.xcodeproj
osx_image: xcode9.3

script: 
 - xcodebuild -scheme Dequable -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.3' test
